### PR TITLE
fix!: Make tracebacks the default

### LINKED ISSUE #32: Make tracebacks the default
For easier debugging

### PR DESCRIPTION
**Pull request by GitaWei**
This PR turns on back tracing as a default option for rust-script.  We should consider if user notification is worthwhile.  A test case which verifies the functionality is included.

Fixes #32

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -331,6 +331,10 @@ fn main() {
     env_logger::init();
 
     let stderr = &mut std::io::stderr();
+
+    //Set back trace early on if it is not set
+    checkset_tracing("1");
```
Comment (epage) [inline src/main.rs:336]: By setting it here, we are affecting
- Our selves
- `cargo build`
- Anything else we might run

Could we  narrow the scope as much as possible to the user application?  I know we call `cargo run` so we might not be able to narrow the scope beyond that for now (later, we could change up that code to call cargo via `escargot` and just call `cargo build` and get the binary from that to then unify the calls ointo the users binary)

The intention is to make it easier for users to debug their own problems.  Think of it like python showing backtraces for your application but not for anything python related.

File: src/main.rs [hunk 2]
```diff
@@ -343,6 +347,16 @@ fn main() {
...
 
+fn checkset_tracing(bt: &'static str) {
+    let _u = match std::env::var_os("RUST_BACKTRACE") {
+        Some(v) => v.into_string().unwrap(),
+        None => {
+            std::env::set_var("RUST_BACKTRACE", bt);
+            bt.to_string()
+        }
+    };
+}
```
Comment (epage) [inline src/main.rs:358]: How come this is getting the new traceback value as a string and then discarding it?

File: src/main.rs [hunk 3]
```diff
@@ -343,6 +347,16 @@ fn main() {
     }
 }
 
+fn checkset_tracing(bt: &'static str) {
```
Comment (epage) [inline src/main.rs:350]: If we are accepting the value as a parameter, should we move the parameter to be using rust types?

File: tests/integration/script.rs [hunk 4]
```diff
@@ -1,4 +1,22 @@
 #[test]
+fn test_script_default_backtrace() {
```
Comment (epage) [inline tests/integration/script.rs:2]: We should probably have a test that also verifies we can override the backtrace value

**Review by epage — COMMENTED** [review]
Thanks!

File: src/main.rs (hunk 2 above)
Comment (GitaWei) [reply src/main.rs:358]: Good point, I'll remove Some(v)... and bt.to_string().  I was initially notifying the user of the setting.

File: src/main.rs (hunk 1 above)
Comment (GitaWei) [reply src/main.rs]: Now passed directly to the cargo cmd construct

File: src/main.rs (hunk 2 above)
Comment (GitaWei) [reply src/main.rs]: It now returns the correct value but does not set a value.

File: tests/integration/script.rs (hunk 4 above)
Comment (GitaWei) [reply tests/integration/script.rs:2]: I don't think we want to override do we?  If it is set to "full" for example we should honor that.

File: src/main.rs (hunk 3 above)
Comment (GitaWei) [reply src/main.rs]: I guess there is no need to pass a parameter in really.  I don't think we will ever set it to something other than 1 or remove it.

File: tests/integration/script.rs (hunk 4 above)
Comment (epage) [reply tests/integration/script.rs:2]: > If it is set to "full" for example we should honor that.

Thats what I mean, having a test that calls `env("RUST_BACKTRACE", "0")` and verifies there is no backtrace.  ie verifying the user has precedence over the default in rust-script.

File: src/main.rs [hunk 5]
```diff
@@ -343,6 +344,15 @@ fn main() {
...
 
+//Set back trace on if it is not set
+fn check_tracing() -> String {
+    let _u = match std::env::var_os("RUST_BACKTRACE") {
+        Some(v) => v.into_string().unwrap(),
+        None => "1".to_string(),
+    };
+    _u
+}
+
```
Comment (epage) [inline src/main.rs:355]: The comment says its going to set it.  `check` I assume is meaning "get" but we aren't properly getting, we are changing the default.

What if we simplified things by getting rid of the function and did

```rust
if std::env::var_os("RUST_BACKTRACE").is_none() {
    cmd.env("RUST_BACKTRACE", "1");
}
```

File: tests/integration/script.rs [hunk 6]
```diff
@@ -1,4 +1,39 @@
...
+    fixture
+        .cmd()
+        .env("RUST_BACKTRACE", "0")
+        .arg("tests/data/script-override-backtrace.rs")
+        .assert()
+        .failure()
+        .stderr_matches(
+            "...
+thread 'main' panicked at 'a pink elephant!', script-override-backtrace.rs:6:5
+...",
```
Comment (epage) [inline tests/integration/script.rs:13]: Are the `...`'s preventing us from confirming that no backtrace was shown?

Comment (GitaWei) [reply tests/integration/script.rs:13]: I'll double check that

File: src/main.rs (hunk 5 above)
Comment (GitaWei) [reply src/main.rs]: Got rid of the function as suggested.

**Comment by epage** [comment]
I'm assuming the failures are more rustup issues that need to be looked into
